### ISSUE TITLE
Mounting paths needed for boot can fail

### ISSUE THREAD

**Issue by m-bdf** [nix-community/impermanence#121]
Booting a system with `environment.persistence."/persistent".directories = [ "/var/lib/nixos" ]` (from the README) fails if /persistent/var/lib/nixos does not exist yet:

```
waiting for device /mnt-root/persistent/var/lib/nixos to appear.......................
Timed out waiting for device /mnt-root/persistent/var/lib/nixos, trying to mount anyway.
mounting /mnt-root/persistent/var/lib/nixos on /var/lib/nixos...
mount: mounting /mnt-root/persistent/var/lib/nixos on /mnt-root/var/lib/nixos failed: No such file or directory

An error occurred in stage 1 of the boot process, which must mount the
root filesystem on `/mnt-root` and then start stage 2. Press one
of the following keys:

  r) to reboot immediately
  *) to ignore the error and continue
```

The init script of boot stage 1 tries to mount non-existent /persistent/var/lib/nixos on /var/lib/nixos, because this path is [needed for boot](https://github.com/NixOS/nixpkgs/blob/5fd439e1ce737fdfb22159faf38fe0be504674e9/nixos/lib/utils.nix#L13-L14). However, the [activation script](https://github.com/nix-community/impermanence/blob/master/create-directories.bash) responsible for creating missing directories is only run after stage 1, so mounting fails.

This issue should occur for any path needed for boot, whose persistent storage does not exist at boot.

**Comment by m-bdf** [comment]
Note that for some reason this is not an issue with `boot.initrd.systemd.enable = true;`

**Comment by Akimitsu333** [comment]
Maybe you need the option `neededForBoot`.

**Comment by m-bdf** [comment]
I agree it looks like this should fix it, but unfortunately it doesn't, my /persistent filesystem is already marked `neededForBoot`.
If it works with systemd-based stage 1, maybe it's a bug in NixOS's traditional shell script stage 1?

**Comment by MrFoxPro** [comment]
For anyone who struggles with this, try:
```nix
boot.initrd.systemd.enable = true;
boot.loader.efi.canTouchEfiVariables = true;
```

**Comment by talyz** [comment]
Please try #172 and see if it fixes this issue for you.

**Comment by visualphoenix** [comment]
Also hitting this with nixos-anywhere and disko - commenting out impermanence allows initial provision with nixos-anywhere, but with it i get:

```
copying path '/nix/store/i8a31irgk06kr01jndjk9dzjwvfknb2r-unit-suid-sgid-wrappers.service' from 'https://cache.nixos.org'...
copying path '/nix/store/bqn3fchv6v8c7ym7zkvn0ks6k66mkc33-linux-6.6.34-modules' from 'https://cache.nixos.org'...
### Installing NixOS ###
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added '192.168.1.19' (ED25519) to the list of known hosts.
installing the boot loader...
Warning: Source directory '/nix/persist/system/etc' does not exist; it will be created for you with the following permissions: owner: 'root:root', mode: '0755'.
mkdir: cannot create directory ‘/nix/persist/system/etc’: No such file or directory
```

**Comment by Curious-r** [comment]
@visualphoenix 
Did you mean it can not find any boot device after reboot?
Just to provide a little inspiration: After installed with nixos-anywhere and impermanece, did you checked if the ESP partation be written actually? If not, maybe you can try to leave 1M before ESP partation in disko config.
