### ISSUE TITLE
Question about Home Manager

### ISSUE THREAD

**Issue by dschrempf** [nix-community/impermanence#123]
Hi!

I am working on activating `impermanence` for my setup, and it works great so far. However, I did not switch over to using a temporary file system, yet, because I am unsure how symbolic links managed by Home Manager are handled. That is, Home Manager creates (many) symbolic links during activation. For example, when enabling `programs.beets`, Home Manager activation creates a symlink from `${HOME}/.config/beets/config.yaml` to the configuration file in the Nix store.

Are these "Home-Manager-Activation" links lost after reboot when using `tmpfs`, or are they somehow recreated by `impermanence` (or Home Manager) after each reboot? If they are lost, do you link all of these files using impermanence? Is this feasable?

Thank you for your help!

**Comment by dschrempf** [comment]
I just had a closer look, and it seems the Home Manager activation script is run at every boot. That's great, so a `tmpfs` should work out of the box. Please let me know, if you have had a different experience! Feel free to close this issue.

**Comment by talyz** [comment]
Indeed, at least as long as you're using the home-manager NixOS module, it should be handled automatically on boot.
