### ISSUE TITLE
permissions on .gnupg

### ISSUE THREAD

**Issue by mogorman** [nix-community/impermanence#14]
I realize this isn't really a bug.

```
    home.persistence."/nix/persist/home/mog" = {
      directories = [
        ".gnupg/private-keys-v1.d" ".gnupg/openpgp-revocs.d"
      ];
      files = [ ".gnupg/trustdb.gpg" ".gnupg/random_seed" ".gnupg/sshcontrol" ".gnupg/pubring.kbx" ];
    };
```

because of how this is done impermanence has to create the .gnupg directory because it does not exist. it creates the .gnupg with mkdir and has standard permissions. and gpg complains
```
gpg: WARNING: unsafe permissions on homedir '/home/mog/.gnupg'
```
chmoding it resolves issue obviously, but I have to do that every boot.

How would you feel about a special check for .gnupg and chmoding it impermanence is going to create it. or is there a better way to solve this problem?

**Comment by cole-h** [comment]
-1 on a special check for .gnupg (I generally think special-casing is a code smell), but +1 on a way to specify permissions. Maybe instead of only accepting a list of strings, also accept a list of attrs in the form of `{ path = ".gnupg/..."; permissions = "700"; /* or permissions = "rwx------"; */ }`?

**Comment by talyz** [comment]
Since the introduction of bind mounts for the home-manager module, this isn't a problem anymore. Simply specify the whole `.gnupg` directory in `directories` and you should be good.

**Comment by lovesegfault** [comment]
Even if you don't want to use home-manager bind mounts, you can still add that one folder to the system-wide bind mounts and it should just work.
