### ISSUE TITLE
Can't rebuild system - getting attributes of path: Permission denied

### ISSUE THREAD

**Issue by n3oney** [nix-community/impermanence#148]
For a while I've been unable to rebuild my system. Every time I try, I get this:
```
error:
       … while setting up the build environment

       error: getting attributes of path '/nix/store/ap6kzvndr3r2sdzipapx5ggpib7xhn52-persist-home-neoney-cache-anyrun-ha-assistsqlite3': Permission denied
```
       
This error will appear for every directory in symlink mode, and for every file. I've changed two dirs from symlinks, but I can't change anything with the files.

My configuration is available at https://github.com/n3oney/nixus. You might not be able to evaluate it, as it requires patched Nix. My impermanence code is in https://github.com/n3oney/nixus/blob/main/modules/misc/impermanence.nix

**Comment by n3oney** [comment]
This seems like a Nix issue for me, as it's also an issue with agenix.

**Comment by Misterio77** [comment]
Hey, did you manage to fix this? Or perhaps have a link to a Nix issue handy? Got that error and can't seem to find much on it. Definitely a regression.

**Comment by Misterio77** [comment]
Actually, found this: https://github.com/NixOS/nix/issues/9579

**Comment by n3oney** [comment]
It was a regression. I downgraded Nix.

**Comment by n3oney** [comment]
I'm personally using nix-super, so I just locked it to commit ba035e1ea339a97e6ba6a1dd79e0c0e334240234.

**Comment by SebTM** [comment]
Can confirm, builds fine on 2.18 but not until 2.21.2 -> will try next release as a fix was merged last week
