### ISSUE TITLE
The importance of persisting `/var/lib/nixos` is not documented

### ISSUE THREAD

**Issue by kuruczgy** [nix-community/impermanence#178]
The examples do show `/var/lib/nixos` being persisted, but it's never mentioned that doing so is vital to the correct functioning of the UID/GID allocation mechanism of NixOS.

If `/var/lib/nixos` is not persisted, UIDs/GIDs are allocated sequentially, and so can shift around across boots if new ones are added to the configuration. It can happen that after a reboot, a file is now randomly owned by a different user.

The documentation should warn about this, and as a longer term solution I would suggest adding an assertion: Only allow `/var/lib/nixos` to not be persisted if all users/groups have explicitly declared ids.

**Comment by kuruczgy** [comment]
Apparently this got recently documented in NixOS: https://github.com/NixOS/nixpkgs/pull/273384
We could just link to this in the README and the option docstring.

**Comment by Guekka** [comment]
Thank you for this issue. I had troubles with folders getting the wrong owner after a reboot and couldn't figure out why

**Comment by kalyanoliveira** [comment]
I would say that the current warning is not sufficient enough:

```
evaluation warning: environment.persistence:
                        Neither /var/lib/nixos nor any of its parents are
                        persisted. This means all users/groups without
                        specified uids/gids will have them reassigned on
                        reboot.
```

This warning is pedantic: it tells you exactly the TECHNICAL extent of what is going to happen. But it doesn't really touch on what can happen given that technical predicament, which is something that more novice users might not be aware of (like me, until now).

This warning should somehow convey this message (perhaps more eloquently phrased):


> If you don't persist /var/lib/nixos, the users/groups/owners of your folders will be swapped when you reboot. This means that a folder that must be owned by, say, `root`, could end up being owned by `copyparty`.

**Comment by kuruczgy** [comment]
Yeah I think this should be an error and not just a warning. I think some people had some weird setups that were getting falsely flagged, and so this was changed to a warning? Idk what would be the blocker for changing it back to an error.
