### ISSUE TITLE
Unpersisted /var/lib/nixos warning doesn't consider regular mounts

### ISSUE THREAD

**Issue by cdombroski** [nix-community/impermanence#200]
Commit 467e24bd041e16a9752de7700d067b2efb9329c9 doesn't take into account situations such as when /var is mounted from a regular filesystem

**Comment by oluceps** [comment]
I got the warning while setting btrfs subvol as /var. Consider adding an option for disabling the warning?

**Comment by chewblacka** [comment]
I have `/var/lib` mounted as a btrfs subvolume so it persists, but I still get the warning:

`Neither /var/lib/nixos nor any of its parents are persisted. This means all users/groups without specified uids/gids will have them reassigned on reboot.`
