### ISSUE TITLE
"Failed unmounting /nix/store" with a bind-mounted `/nix`

### ISSUE THREAD

**Issue by Nadrieril** [nix-community/impermanence#21]
I just changed my system to have a tmpfs root, and found impermanence amazing! But my `/nix` is bind-mounted and I get the following error on boot:
```
Nov 09 20:41:02 meluin systemd[1]: Listening on Journal Audit Socket.
Nov 09 20:41:02 meluin systemd[1]: Listening on Journal Socket (/dev/log).
Nov 09 20:41:02 meluin systemd[1]: Listening on udev Control Socket.
Nov 09 20:41:02 meluin systemd[1]: Listening on udev Kernel Socket.
Nov 09 20:41:02 meluin systemd[1]: Unmounting /nix/store...
Nov 09 20:41:02 meluin systemd[736]: nix-store.mount: Failed to connect stdout to the journal socket, ignoring: No such file or directory
Nov 09 20:41:02 meluin systemd[1]: nix-store.mount: Mount process exited, code=exited, status=32/n/a
Nov 09 20:41:02 meluin systemd[1]: Failed unmounting /nix/store.
```
So far everything seems to be working normally, but I don't really know what this means so I hope nothing is broken.

**Comment by talyz** [comment]
Hi! Glad you like it! :)

My `/nix` is a btrfs subvolume and I see the same error in my log whether impermanence is used or not and is likely a NixOS bug. However, it hasn't (to my knowledge) affected my system negatively in any way.

**Comment by Nadrieril** [comment]
Hm ok good to know. I _think_ it's trying to unmount /nix from the initrd root so it shouldn't be too bad if that fails.

**Comment by dschrempf** [comment]
Do you still have this problem? I am using `tmpfs` and also get "failed unmount /nix` error messages. (I have my persisted directories in `/nix`).

**Comment by Nadrieril** [comment]
Yep, still happening

**Comment by iclanzan** [comment]
I am seeing this error when shutting down. Also on `tmpfs` root and with all persisted things under `/nix`.

**Comment by mcsimw** [comment]
I have tested various filesystem configurations in nixos and I only get this error on shutdown when / is mounted to a tmpfs and /nix is mounted to an xfs partition.  ext4, btrfs, zfs, no issues at all with the / mounted to a tmpfs.

**Comment by dschrempf** [comment]
I use `tmpfs` for root and a LUKS encrypted `ext4` partition which is mounted at `/nix`, and I still get this error on every shutdown.

**Comment by tensor5** [comment]
> I use `tmpfs` for root and a LUKS encrypted `ext4` partition which is mounted at `/nix`, and I still get this error on every shutdown.

I have exactly the same problem.

**Comment by dschrempf** [comment]
I am also still having this problem, I think it is only solvable by having a separate partition for persistently stored files.

**Comment by tomasmark79** [comment]
Same here

**Comment by dschrempf** [comment]
For the record, this is still an issue, and I think it is only solvable by having a separate partition for all persistent files. The setup instructions are clearly advocating for such a setup. The only action items I can think of are
- Warmly suggest a separate `persistent` partition, and
- Warn against merging `persistent` into the `/nix` partition.
