### ISSUE TITLE
ZFS not compatible with PR #172

### ISSUE THREAD

**Issue by nakoo** [nix-community/impermanence#216]
This PR (https://github.com/nix-community/impermanence/pull/172) is not compatible with ZFS. It relies on the device defined in `fileSystems.<name>.device`, but for instance, if `fileSystems."/persist".device = "zpool/persist"`, the corresponding `zpool-persist.device` won't exist in ZFS.

To make it work with ZFS, the code needs to be modified.

```nix
boot.initrd.systemd.services.create-needed-for-boot-dirs = {
  after = lib.mkForce ["zfs-import-<pool>.service"];
  wants = lib.mkForce ["zfs-import-<pool>.service"];
  unitConfig.DefaultDependencies = "no";
};
```
I'm not sure why `unitConfig.DefaultDependencies = "no"` wasn't set in the first place though.

**Comment by talyz** [comment]
I see. I don't use ZFS, so I'll for sure need some help with this. Would it perhaps suffice to make run after `zfs-import.target`? Regarding `DefaultDependencies`, it's not set to `false` because that wasn't necessary in testing.

**Comment by nakoo** [comment]
> I see. I don't use ZFS, so I'll for sure need some help with this. Would it perhaps suffice to make run after `zfs-import.target`? Regarding `DefaultDependencies`, it's not set to `false` because that wasn't necessary in testing.

Yes, `zfs-import.target` works. I tested it on my machine, and it booted successfully.

**Comment by talyz** [comment]
Please try #220.
