### ISSUE TITLE
Merged change into nixpkgs causes problems with /etc/machine-id if it is a bind mount

### ISSUE THREAD

**Issue by kaldyr** [nix-community/impermanence#229]
The service systemd-machine-id-commit.service will now cause problems if /etc/machine-id is configured as a bind mount.  It may work if it is a symlink.

On rebuild:
```
warning: the following units failed: systemd-machine-id-commit.service
× systemd-machine-id-commit.service - Save Transient machine-id to Disk
     Loaded: loaded (/etc/systemd/system/systemd-machine-id-commit.service; enabled; preset: ignored)
     Active: failed (Result: exit-code) since Thu 2024-10-31 17:08:10 PDT; 348ms ago
 Invocation: 376b00e9024546a58aead7f2f41f33d3
       Docs: man:systemd-machine-id-commit.service(8)
    Process: 15455 ExecStart=systemd-machine-id-setup --commit (code=exited, status=1/FAILURE)
   Main PID: 15455 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
   Mem peak: 1.8M
        CPU: 8ms

Oct 31 17:08:10 mjolnir systemd[1]: Starting Save Transient machine-id to Disk...
Oct 31 17:08:10 mjolnir systemd-machine-id-setup[15455]: /etc/machine-id is not on a temporary file system.
Oct 31 17:08:10 mjolnir systemd[1]: systemd-machine-id-commit.service: Main process exited, code=exited, status=1/FAILURE
Oct 31 17:08:10 mjolnir systemd[1]: systemd-machine-id-commit.service: Failed with result 'exit-code'.
Oct 31 17:08:10 mjolnir systemd[1]: Failed to start Save Transient machine-id to Disk.
warning: error(s) occurred while switching to the new configuration

```

Merged PR: [nixpkgs:351151](https://github.com/NixOS/nixpkgs/pull/351151)

Some discussion there.

Temporary workaround:
```
boot.initrd.systemd.suppressedUnits = [ "systemd-machine-id-commit.service" ];
systemd.suppressedSystemUnits = [ "systemd-machine-id-commit.service" ];
````

**Comment by jrbp** [comment]
If using a symlink doesn't cause the issue could we do:
```nix
systemd.tmpfiles.rules =  [
  "L /etc/machine-id - - - - /persist/etc/machine-id"
]
```
Or is there an issue like tmpfiles being created at the wrong time at boot compared to when this service runs?

Is it possible to make files be symlinks with the nixos impermanence module? It seems the `method` option that directories doesn't exist for files.

**Comment by willbush** [comment]
I briefly tried the symlink workaround, but something stomped on it (think when rebooting) and just created a new machine-id file.

**Comment by kaldyr** [comment]
That was intended as a temporary workaround.  Per the discussion:  It will work on existing machines, but may cause problems with machines that are created for the first time.  Will the /etc/machine-id file be generated without that service?

**Comment by talyz** [comment]
Please see #242 for a follow-up fix to this issue.
