### ISSUE TITLE
Boot dependencies broken when persistence directory is a bind mount

### ISSUE THREAD

**Issue by Majiir** [nix-community/impermanence#237]
Consider this simplified example:

```nix
{
  fileSystems = {
    "/nixos" = {
      device = "/dev/sda1";
      fsType = "ext4";
      neededForBoot = true;
    };

    "/persist" = {
      device = "/nixos/persist";
      options = [ "bind" ];
    };
  };

  environment.persistence."/persist" = {
    directories = [
      "/var/lib/nixos"
    ];
  };
}
```

When using systemd initrd, impermanence creates a `create-needed-for-boot-dirs.service` unit with `Requires=nixos-persist.device` and `Wants=nixos-persist.device`. No such device exists, so boot hangs until the device unit times out.

The relevant logic is [here](https://github.com/nix-community/impermanence/blob/3ed3f0e/nixos.nix#L752-L759).

We should check whether the filesystem is a bind mount and create the unit name accordingly. NixOS has [this check](https://github.com/NixOS/nixpkgs/blob/8b125fe422e792de8211b305328500e12549ea2f/nixos/modules/tasks/filesystems.nix#L197) for whether a filesystem is a bind mount.

**Comment by Luminger** [comment]
I'm experiencing the same hangs you describe but with a different setup. I'm using `microvm.nix` with `impermanence`, where `/persist`:

```nix
{
  microvm.shares = [
    {
      source = "/mnt/pool/vm/persist";
      mountPoint = "/persist";
      tag = "persist";
      proto = "virtiofs";
    }
  ];
}
```

The issue you described is the same, `persist.device` units are placed into `Requires=` and `Wants=`.

The fix you proposed doesn't work for me as the backing filesystem is `virtiofs` and there's no bind option present. It would require another check to see if the filesystem is `virtiofs`, but this doesn't scale for other filesystems (like `p9`) that also lack devices. I think a generalized solution would be required here.

**Comment by frantisekhanzlikbl** [comment]
Another useful filesystem with no device units is `tmpfs` (plus `ramfs`, whatever one might need that for). A general solution really is needed.

I'm using the following patch to work around this temporarily:
```patch
diff --git a/nixos.nix b/nixos.nix
index cdad872..a633edc 100644
--- a/nixos.nix
+++ b/nixos.nix
@@ -750,12 +750,11 @@ in
               in
               concatMap matchFileSystems persistentStoragePaths;
             deviceUnits = unique
-              (map
+              (concatMap
                 (fs:
-                  if fs.fsType == "zfs" then
-                    "zfs-import.target"
-                  else
-                    "${(escapeSystemdPath (getDevice fs))}.device")
+                  if fs.fsType == "tmpfs" then [] else
+                  if fs.fsType == "zfs" then [ "zfs-import.target" ] else
+                  [ "${(escapeSystemdPath (getDevice fs))}.device" ])
                 fileSystems);
             createNeededForBootDirs = ''
               ${concatMapStrings mkMount fileSystems}
```

**Comment by Luminger** [comment]
@talyz The proposed fix only fixes the issue for bind, it's still broken for tmpfs and Virtiofsd.

The proper fix would be ageneralized solution, please reopen the issue.

**Comment by talyz** [comment]
@Luminger Please try out #245, which has a more generic approach to solving this.

**Comment by Luminger** [comment]
@talyz: Thank you :) Just tested out #245 in my setup, and it works for my case. The bogus `.device` dependencies are no longer added.

Again, thank you for investing time into fixing it in a generic way!

**Comment by talyz** [comment]
Great! Thanks for the quick testing!
