### ISSUE TITLE
NixOS 24.11 zfs related scripts need to be in postResumeCommands

### ISSUE THREAD

**Issue by Hyffer** [nix-community/impermanence#239]
according to [NixOS 24.11 release note](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md): ZFS now imports its pools in postResumeCommands rather than postDeviceCommands. If you had postDeviceCommands scripts that depended on ZFS pools being imported, those now need to be in postResumeCommands.

so this is now broken:
https://github.com/nix-community/impermanence/blob/3ed3f0eaae9fcc0a8331e77e9319c8a4abd8a71a/nixos.nix#L778

and something like "filesystem 'zpermanence/permanence' cannot be mounted. unable to open the dataset" will manifest itself on NixOS Stage 1.

### Solution
Change it to `postResumeCommands` could fix, but I am not sure if this will break other stuff.

**Comment by talyz** [comment]
It should be fine to run everything in `postResumeCommands`, since that's still before any file systems are mounted, which is what we need. I've added this fix to #245, so please try it out.

**Comment by Hyffer** [comment]
It works as expected on my zfs system!
