### ISSUE TITLE
Does the flake.nix works with home-manager.nix?

### ISSUE THREAD

**Issue by bbigras** [nix-community/impermanence#25]
I'm guessing it only works for `nixos.nix`.

**Comment by cole-h** [comment]
Indeed, it only works for `nixos.nix` in its current form. However, you can always add `"${inputs.impermanence}/home-manager.nix"` to your modules.

**Comment by bbigras** [comment]
Thanks!

**Comment by blaggacao** [comment]
Is this an issue worth keeping open?

**Comment by bbigras** [comment]
Why not expose home-manager.nix in flake.nix?

**Comment by lovesegfault** [comment]
I don't think it's possible yet to do that with flakes? They only expose a `nixosModules` IIRC

**Comment by blaggacao** [comment]
[This PR has context / discussion / references](https://github.com/divnix/devos/pull/156/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R59-R62)

**Comment by Th3Whit3Wolf** [comment]
I believe this should be doable, [nix-doom-emacs](https://github.com/vlaci/nix-doom-emacs) does it. Unless I am missing something.
