### ISSUE TITLE
Issue when installing NixOS with impermanence

### ISSUE THREAD

**Issue by jmc-figueira** [nix-community/impermanence#34]
Hello,

I recently decided to try out the tmpfs root setup described [here](https://elis.nu/blog/2020/06/nixos-tmpfs-as-home/).

I used the following configuration for NixOS:

```Nix
environment = {
  persistence."/persist" = {
    directories = [
      "/etc/nixos"
      "/etc/NetworkManager/system-connections"
      "/var/lib/bluetooth"
    ];

    files = [
      "/etc/machine-id"
    ];
  };
};
```

And for home-manager:

```Nix
home.persistence."/persist/home/jmc-figueira" = {
  directories = [
    "Documentos"
    "Imagens"
    "Jogos"
    "Música"
    "Transferências"
    "Vídeos"
  ];
  files = [
    ".bash_history"
    ".zsh_history"
  ];
};
```

However, upon running `nixos-install`, the following error occurred:

```
realpath: /persist/etc/nixos: No such file or directory
Error when executing realpath "$sourceBase$target" at line 38!
Error when executing realSource="$(realpath "$sourceBase$target")" at line 38!
realpath: /persist/etc/NetworkManager/system-connections: No such file or directory
Error when executing realpath "$sourceBase$target" at line 38!
Error when executing realSource="$(realpath "$sourceBase$target")" at line 38!
realpath: /persist/var/lib/bluetooth: No such file or directory
Error when executing realpath "$sourceBase$target" at line 38!
Error when executing realSource="$(realpath "$sourceBase$target")" at line 38!
Warning: Source directory '/persist/etc' does not exist: it will be created for you. Make sure the permissions are correct!
Activation script snippet 'createDirsIn--persist' failed (1)
```

This results in an empty `/persist/etc` folder and nothing else.

Is there any prior setup I should be aware of before using impermanence?

**Comment by jmc-figueira** [comment]
I had not realized I had to manually create the folders in `/persist` first. After I did that, it worked. Closing this issue...

**Comment by talyz** [comment]
Hi! Thank you for reporting this! You should not have to create the directory structure in your persistence root. It should create the directory for you with the message
>Warning: Source directory `dirname` does not exist; it will be created for you. Make sure the permissions are correct!
This is a bug in the `create-directories.bash` script. `realpath` cannot be passed a path to a file in a nonexistent directory.

**Comment by jmc-figueira** [comment]
I see. The message you mention appears, indeed, but the script still fails. Perhaps it's something to do with the order of operations? `realpath` should probably be called after the directory is created, I'm guessing.

**Comment by talyz** [comment]
Can you try #37? It should solve your issue.

**Comment by jmc-figueira** [comment]
It did solve that previous issue; however, the files inside the directories are not copied to the persistence root (for instance, `configuration.nix` in `/etc/nixos/`).

**Comment by talyz** [comment]
Great! I'll close this now, then.

No, they wouldn't be - we never copy or move files into persistent storage. If you want the files to exist in persistent storage before the bind mounts and links are set up, you need to create them there to begin with.

**Comment by jmc-figueira** [comment]
Oh, so this bug was just about the directory structure then. I see. Thanks for the quick fix!

**Comment by talyz** [comment]
Yes, exactly. No problem!
