### ISSUE TITLE
impermanence doesn't work with `qemu-vm.nix built systems.

### ISSUE THREAD

**Issue by tomprince** [nix-community/impermanence#50]
I'm using nixos testing machinery to setup several nixos VMs for ad-hoc testing of a distributed service. I want to persist some state between run (in particular ssh host keys and tailscale configuration). I tried using impermanence, but it looks like it doesn't work, since `qemu-vm.nix` overrides `config.fileSystems` set by impermanence.

**Comment by talyz** [comment]
Yeah, that's correct. I don't think there's much we can do about it here, though. It sounds like an issue to raise in nixpkgs.
