### ISSUE TITLE
home-manager: race condition with certain services

### ISSUE THREAD

**Issue by lourkeur** [nix-community/impermanence#60]
I use `syncthing` via home-manager, so I have to bind-mount its mutable directories. The problem is that both the bind-mount and `syncthing` itself are started via systemd, so `syncthing` may start and recreate its configuration from scratch before `bindfs` gets a chance to do its thing.

My current solution is to turn the `bindfs` unit into a `forking`-type systemd unit and make the `syncthing` unit depend on it. Is there a known better solution? If not I will PR my patch.

**Comment by talyz** [comment]
I've created a follow-up PR (#62) to address the second part of your issue. Can you try it out without adding dependencies to the syncthing unit and see if it still works?
