### ISSUE TITLE
Kernel panic resulting from a possible precedence issue

### ISSUE THREAD

**Issue by jmc-figueira** [nix-community/impermanence#77]
Hi!

I was previously using impermanence pinned to commit 58558845bc68dcf2bb32caa80564f7fe3f6cbc61 and, having seen the recent improvements to the module, decided to update to commit ff540dbe20556f6119d80f5c79796a0698a4ee38.

Unfortunately, somewhere in between, possibly due to the addition of #44, I believe that the `/etc/NIXOS` file, which I currently have configured to be persisted, as it is stated to be necessary for NixOS to recognize its own root partition, became involved in a precedence issue, where it causes NixOS to panic due to its potentially premature loading. The following screenshot exemplifies this occurrence (sorry for the poor quality but, as I do not have `systemctl` logs persisted, I am unable to directly copy the relevant log lines):

![image](https://user-images.githubusercontent.com/6634716/152626175-df711657-f57b-4e20-b235-e5dff3da42f1.png)

What occurs after the `/etc/NIXOS` clash is that systemd is not found and the boot process is aborted.

I apologize for the vagueness of my explanation, but I am at a loss as to what else may be the root cause of this issue, as well as any potential workarounds.

**Comment by maydayv7** [comment]
`/etc/NIXOS` is automatically generated, and needn't be persisted. Works perfectly fine for me that way

**Comment by etu** [comment]
> I believe that the `/etc/NIXOS` file, which I currently have configured to be persisted, as it is stated to be necessary for NixOS to recognize its own root partition, became involved in a precedence issue, where it causes NixOS to panic due to its potentially premature loading.

Where is this stated to be a necessary file? I'm running all my systems on tmpfs as root and ZFS for persistence mounted in where needed. I've never even looked at this file before.

**Comment by talyz** [comment]
Yeah, the `/etc/NIXOS` file is automatically created on boot by the `setup-etc.pl` script, so you don't need to persist it. However, the kernel panic is a bug that should be fixed. It probably occurs because the script exits with an error when a conflicting file is found. I'll fix that.
