### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by shadowrylander** [nix-community/impermanence#78]
Hello!

`While setting up the build environment: executing '/nix/store/...-bash-5.1-p8/bin/bash': Argument list too long`.

I'm getting this while installing nixos with a presumably large number of files and directories.

How might I go about fixing this?

Thank you kindly for the help!

**Comment by talyz** [comment]
Do you have more context info? Where is the argument list in question?

**Comment by shadowrylander** [comment]
All the files [here](https://github.com/shadowrylander/shadowrylander)! 😭

**Comment by talyz** [comment]
It should at least say what it's trying to build before the error message. Can you paste the whole output, even if it doesn't look relevant? Is this using the NixOS or the home-manager module?

**Comment by shadowrylander** [comment]
NixOS, and I'm just about to restart the install; I'll paste the output in a bit!

**Comment by shadowrylander** [comment]
Here it is! https://github.com/shadowrylander/shadowrylander/blob/main/tmp

**Comment by shadowrylander** [comment]
So I invalidated the tarball cache, wiped out the mountpoint's nix directory, and reinstalled; same error.

**Comment by talyz** [comment]
Well, if that doesn't solve it, I have no idea what the issue is :shrug: How did you fetch the branch?

**Comment by shadowrylander** [comment]
`fetchGit`; I'm currently trying again from a fresh install medium instance.

**Comment by shadowrylander** [comment]
Well that didn't work...

**Comment by shadowrylander** [comment]
Wait, wait, wait, wait, wait; just realized you're using a pull-request branch!

**Comment by shadowrylander** [comment]
YES! YES IT WORKS! THANK YOU SO MUCH!
