### ISSUE TITLE
chroot: failed to run command 'systemd-tmpfiles': No such file or directory

### ISSUE THREAD

**Issue by shadowrylander** [nix-community/impermanence#79]
Hello!

When installing with the module I get `chroot: failed to run command 'systemd-tmpfiles': No such file or directory` and `chroot: failed to run command '/run/current-system/bin/switch-to-configuration': No such file or directory`. In relation to [this issue](https://github.com/nix-community/impermanence/issues/78), this is when I use a smaller number of files and directories.

Thank you kindly for the help!

**Comment by shadowrylander** [comment]
Actually, this happens right after the statement `A file already exists at 'path'`!

**Comment by shadowrylander** [comment]
The issue can be resolved by simply moving the `targetFile` to the `mountPoint`, and _then_ linking:
```bash
mv ${mountPoint} ${targetFile}
mount -o bind ${targetFile} ${mountPoint}
```

I feel that, since you're already checking for a link and a mount, we can assume that the anything else would be a file or a directory, and simply treat the `mountPoint` as the `targetFile`, move it to the persistent directory, and then bind-mount them together. However, I still feel as though I'm missing something...

**Comment by talyz** [comment]
Hi!

The error when activating the new configuration should be resolved by #84, I hope.

We never move any files from ephemeral storage to persistent storage, since that could be potentially dangerous on a running system - we don't know if the files are in use or about to be.

**Comment by shadowrylander** [comment]
... Oops... Forgot about that situation... 😅 I'll return the installation and report back! Thanks for all the help!

**Comment by shadowrylander** [comment]
Well, I can close this one, too! Sorry; forgot to do so, and thanks again for all the help!

**Comment by talyz** [comment]
No problem! :)
