### ISSUE TITLE
issues with Steam

### ISSUE THREAD

**Issue by jackinloadup** [nix-community/impermanence#91]
I'm having issues with games not being able to load. From what I have been able to piece together it seems to be related to wiring up graphics libraries or something. I'm just testing the waters here to see if anyone else has seen this.

The only directory I have under impermanence for steam is `.local/share/Steam`. Maybe I'm missing something else?

```
ERROR: ld.so: object '/home/--/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

I've tried things like link among other things.
```
LD_LIBRARY_PATH=~/.steam/bin32:$LD_LIBRARY_PATH steam
```

Oddly this exists and and I can view the executable but can't run it. Not sure if it's related
```
$ /home/--/.local/share/Steam/ubuntu12_32/reaper
zsh: no such file or directory: /home/--/.local/share/Steam/ubuntu12_32/reaper
```

Thanks for any help!

**Comment by talyz** [comment]
Does it work as expected when you're not using impermanence?

**Comment by jackinloadup** [comment]
The few times I've tried to resolve the issue I'm now pretty sure it's related to sway. I'll close the issue and reopen if I can provide more information.

**Comment by jackinloadup** [comment]
I was using the 21.11 release with select packages from unstable. I temporally switched completely to unstable and now steam works without issue.

I hope the 22.05 release will have the relevant updates. Either way an FYI for anyone else who lands here.
